# config.yaml
credentials:
  usernames:
    admin:
      email: admin@example.com
      name: Administrator
      password: "$2b$12$presUdW8I9JiaPSr7za9/OQuAVauw6/YWkXdKpxNPfySlt.J19EAC"
    user:
      email: user@example.com
      name: Standard User
      password: "$2b$12$pa39YZXrPc83KCJOOFdlAeeJKpOF.8vKxYIRZCGXdFZJEt2Wl7F3a"
    user1:
      email: user1@example.com
      name: User One
      password: "$2b$12$h9utmW.dmlTAPkrLZIAK8uvqwyhaBVcRtVgdRqbcTLXvRSDRniAOu"

cookie:
  expiry_days: 30
  key: "trip_logger_random_key_999"
  name: "trip_logger_cookie"

pre-authorized:
  emails:
    - admin@example.com
